name: iyzico
description: This package provides some Iyzico requests these are payment, threed payment, bin etc.
version: 0.1.1+3
repository: https://github.com/yusufgngor/iyzico_dart
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  crypto: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.12
