name: iyzico
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/yusufgngor/iyzico_dart
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  crypto: ^3.0.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
