name: iyzico
description: This package provides some Iyzico requests. You can request bin number, installment info, payment, threeds payment initialize, threeds payment create, Checkout form initialize, Checkout form retrive by using this package. 
version: 0.1.1
repository: https://github.com/yusufgngor/iyzico_dart
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  crypto: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.12
